import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.download': 'Download',
    'nav.faq': 'FAQ',
    'nav.support': 'Support',
    'nav.dashboard': 'Dashboard',
    'nav.install': 'Install',
    
    // Hero
    'hero.badge': 'Military-Grade Encryption',
    'hero.title1': 'Secure Your Digital',
    'hero.title2': 'Privacy Today',
    'hero.subtitle': 'Browse the internet safely with our lightning-fast VPN. Available on all your devices — Windows, Mac, Linux, Android, and iOS.',
    'hero.cta.trial': 'Start Free Trial',
    'hero.cta.learn': 'Learn More',
    'hero.trust.nolog': 'No-Log Policy',
    'hero.trust.countries': '50+ Countries',
    'hero.trust.encryption': 'AES-256 Encryption',
    
    // Features
    'features.title': 'Why Choose SecureVPN?',
    'features.subtitle': 'Industry-leading features to keep you safe online',
    'features.security.title': 'Military-Grade Security',
    'features.security.desc': 'AES-256 encryption protects your data from hackers and surveillance.',
    'features.speed.title': 'Lightning Fast Speeds',
    'features.speed.desc': 'Optimized servers ensure you never sacrifice speed for security.',
    'features.global.title': 'Global Server Network',
    'features.global.desc': 'Connect to 50+ countries and access content from anywhere.',
    'features.nolog.title': 'No-Log Policy',
    'features.nolog.desc': 'We never track, collect, or share your browsing data.',
    'features.anonymous.title': 'Anonymous Browsing',
    'features.anonymous.desc': 'Hide your IP address and browse the web completely anonymously.',
    'features.bandwidth.title': 'Unlimited Bandwidth',
    'features.bandwidth.desc': 'Stream, download, and browse without any data caps.',
    'features.platforms': 'Available on All Your Devices',
    
    // Pricing
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your needs. Cancel anytime.',
    'pricing.free': 'Free',
    'pricing.standard': 'Standard',
    'pricing.premium': 'Premium',
    'pricing.forever': 'forever',
    'pricing.month': '/month',
    'pricing.free.desc': 'Basic protection for casual users',
    'pricing.standard.desc': 'Complete protection for individuals',
    'pricing.premium.desc': 'Maximum security for power users',
    'pricing.popular': 'Most Popular',
    'pricing.startFree': 'Start Free',
    'pricing.getStarted': 'Get Started',
    'pricing.guarantee': '30-day money-back guarantee on all paid plans',
    'pricing.device': 'Device',
    'pricing.devices': 'Devices',
    'pricing.unlimited': 'Unlimited',
    'pricing.serverLocations': 'Server Locations',
    'pricing.basicEncryption': 'Basic Encryption',
    'pricing.limitedBandwidth': 'Limited Bandwidth (500MB/day)',
    'pricing.unlimitedData': 'Unlimited Data',
    'pricing.prioritySupport': 'Priority Support',
    'pricing.aes256': 'AES-256 Encryption',
    'pricing.unlimitedBandwidth': 'Unlimited Bandwidth',
    'pricing.adBlocker': 'Ad & Malware Blocker',
    'pricing.emailSupport': 'Email Support',
    'pricing.wireguard': 'AES-256 + WireGuard',
    'pricing.dedicatedIP': 'Dedicated IP Option',
    'pricing.247Support': '24/7 Priority Support',
    
    // Download
    'download.title': 'Download SecureVPN',
    'download.subtitle': 'Get started in minutes. Available on all major platforms.',
    'download.windows': 'Windows',
    'download.windows.desc': 'Windows 10/11 64-bit',
    'download.windows.btn': 'Download for Windows',
    'download.macos': 'macOS',
    'download.macos.desc': 'macOS 12.0 or later',
    'download.macos.btn': 'Download for Mac',
    'download.linux': 'Linux',
    'download.linux.desc': 'Ubuntu, Debian, Fedora',
    'download.linux.btn': 'Download for Linux',
    'download.android': 'Android',
    'download.android.desc': 'Android 8.0 or later',
    'download.android.btn': 'Download APK',
    'download.ios': 'iOS',
    'download.ios.desc': 'iOS 14.0 or later',
    'download.ios.btn': 'App Store',
    'download.help': 'Need help installing? Check our',
    'download.guide': 'Installation Guide',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about SecureVPN',
    'faq.q1': 'What is a VPN and why do I need one?',
    'faq.a1': 'A VPN (Virtual Private Network) encrypts your internet connection and hides your IP address. This protects your data from hackers on public WiFi, prevents your ISP from tracking your browsing, and lets you access geo-restricted content securely.',
    'faq.q2': 'How many devices can I connect?',
    'faq.a2': 'It depends on your plan. The Free plan supports 1 device, Standard supports 5 devices, and Premium allows unlimited simultaneous connections. All your devices stay protected with a single account.',
    'faq.q3': 'Will a VPN slow down my internet?',
    'faq.a3': 'Modern VPNs like SecureVPN use optimized protocols that minimize speed loss. Most users experience less than 10% speed reduction. Our WireGuard protocol on Premium plans offers near-native speeds.',
    'faq.q4': 'Do you keep logs of my activity?',
    'faq.a4': 'No. We operate under a strict no-logs policy. We don\'t track, collect, or share your browsing activity, connection timestamps, or IP addresses. Your privacy is our priority.',
    'faq.q5': 'Can I use SecureVPN for streaming?',
    'faq.a5': 'Yes! SecureVPN works great for streaming. Our servers are optimized to bypass geo-restrictions, allowing you to access content from different regions on platforms like Netflix, Disney+, and more.',
    'faq.q6': 'How do I install SecureVPN?',
    'faq.a6': 'Simply download the app for your platform from our Download section, install it, and log in with your account. The app will automatically connect you to the best server. Most users are up and running in under 2 minutes.',
    'faq.q7': 'What payment methods do you accept?',
    'faq.a7': 'We accept all major credit cards (Visa, Mastercard, American Express), PayPal, and cryptocurrency (Bitcoin, Ethereum). All payments are processed securely.',
    'faq.q8': 'Is there a money-back guarantee?',
    'faq.a8': 'Yes! All paid plans come with a 30-day money-back guarantee. If you\'re not completely satisfied, contact our support team for a full refund, no questions asked.',
    
    // Contact
    'contact.title': 'Contact Support',
    'contact.subtitle': 'Our team is here to help you 24/7',
    'contact.getInTouch': 'Get in Touch',
    'contact.description': 'Have questions or need help? Our dedicated support team is available around the clock to assist you with any issues.',
    'contact.email': 'Email Support',
    'contact.liveChat': 'Live Chat',
    'contact.liveChat.desc': 'Available 24/7 in-app',
    'contact.responseTime': 'Response Time',
    'contact.responseTime.desc': 'Usually within 2 hours',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'How can we help?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Describe your issue or question...',
    'contact.form.send': 'Send Message',
    'contact.toast.title': 'Message Sent!',
    'contact.toast.desc': 'We\'ll get back to you within 24 hours.',
    
    // Footer
    'footer.description': 'Your trusted partner for online privacy and security.',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.aboutUs': 'About Us',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.helpCenter': 'Help Center',
    'footer.contact': 'Contact',
    'footer.status': 'Status',
    'footer.terms': 'Terms',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.gdpr': 'GDPR',
    'footer.licenses': 'Licenses',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy',
    'footer.cookies': 'Cookies',
    
    // Dashboard
    'dashboard.home': 'Home',
    'dashboard.connecting': 'Connecting...',
    'dashboard.connected': 'Connected',
    'dashboard.disconnected': 'Disconnected',
    'dashboard.connectSecure': 'Connect for secure browsing',
    'dashboard.time': 'Time',
    'dashboard.download': 'Download',
    'dashboard.upload': 'Upload',
    'dashboard.totalDownload': 'Total Download',
    'dashboard.totalUpload': 'Total Upload',
    'dashboard.ping': 'Ping',
    'dashboard.encryption': 'Encryption',
    'dashboard.activeProtection': 'Active Protection',
    'dashboard.killSwitch': 'Kill Switch',
    'dashboard.dnsProtection': 'DNS Protection',
    'dashboard.autoReconnect': 'Auto-Reconnect',
    'dashboard.servers': 'Servers',
    'dashboard.server': 'server',
    'dashboard.load': 'load',
    'dashboard.premium': 'Premium',
    'dashboard.upgradePremium': 'Upgrade to Premium',
    'dashboard.upgradeDesc': 'Access all servers with unlimited speed',
    'dashboard.viewPlans': 'View Plans',
  },
  ru: {
    // Navbar
    'nav.home': 'Главная',
    'nav.features': 'Функции',
    'nav.pricing': 'Цены',
    'nav.download': 'Скачать',
    'nav.faq': 'FAQ',
    'nav.support': 'Поддержка',
    'nav.dashboard': 'Панель',
    'nav.install': 'Установить',
    
    // Hero
    'hero.badge': 'Шифрование военного уровня',
    'hero.title1': 'Защитите Вашу',
    'hero.title2': 'Конфиденциальность',
    'hero.subtitle': 'Безопасно пользуйтесь интернетом с нашим молниеносным VPN. Доступно на всех ваших устройствах — Windows, Mac, Linux, Android и iOS.',
    'hero.cta.trial': 'Начать бесплатно',
    'hero.cta.learn': 'Узнать больше',
    'hero.trust.nolog': 'Без логов',
    'hero.trust.countries': '50+ стран',
    'hero.trust.encryption': 'Шифрование AES-256',
    
    // Features
    'features.title': 'Почему SecureVPN?',
    'features.subtitle': 'Лучшие функции для вашей безопасности онлайн',
    'features.security.title': 'Военное шифрование',
    'features.security.desc': 'AES-256 шифрование защищает ваши данные от хакеров.',
    'features.speed.title': 'Молниеносная скорость',
    'features.speed.desc': 'Оптимизированные серверы без потери скорости.',
    'features.global.title': 'Глобальная сеть',
    'features.global.desc': 'Подключайтесь к 50+ странам мира.',
    'features.nolog.title': 'Без логов',
    'features.nolog.desc': 'Мы никогда не отслеживаем ваши данные.',
    'features.anonymous.title': 'Анонимность',
    'features.anonymous.desc': 'Скройте IP адрес и будьте анонимны.',
    'features.bandwidth.title': 'Безлимитный трафик',
    'features.bandwidth.desc': 'Стримьте и скачивайте без ограничений.',
    'features.platforms': 'Доступно на всех устройствах',
    
    // Pricing
    'pricing.title': 'Простые и прозрачные цены',
    'pricing.subtitle': 'Выберите план под ваши нужды. Отмена в любое время.',
    'pricing.free': 'Бесплатно',
    'pricing.standard': 'Стандарт',
    'pricing.premium': 'Премиум',
    'pricing.forever': 'навсегда',
    'pricing.month': '/месяц',
    'pricing.free.desc': 'Базовая защита для начинающих',
    'pricing.standard.desc': 'Полная защита для пользователей',
    'pricing.premium.desc': 'Максимальная защита',
    'pricing.popular': 'Популярный',
    'pricing.startFree': 'Начать',
    'pricing.getStarted': 'Начать',
    'pricing.guarantee': '30-дневная гарантия возврата',
    'pricing.device': 'Устройство',
    'pricing.devices': 'Устройств',
    'pricing.unlimited': 'Без лимита',
    'pricing.serverLocations': 'Локаций серверов',
    'pricing.basicEncryption': 'Базовое шифрование',
    'pricing.limitedBandwidth': 'Лимит (500МБ/день)',
    'pricing.unlimitedData': 'Безлимитные данные',
    'pricing.prioritySupport': 'Приоритетная поддержка',
    'pricing.aes256': 'Шифрование AES-256',
    'pricing.unlimitedBandwidth': 'Безлимитный трафик',
    'pricing.adBlocker': 'Блокировка рекламы',
    'pricing.emailSupport': 'Email поддержка',
    'pricing.wireguard': 'AES-256 + WireGuard',
    'pricing.dedicatedIP': 'Выделенный IP',
    'pricing.247Support': 'Поддержка 24/7',
    
    // Download
    'download.title': 'Скачать SecureVPN',
    'download.subtitle': 'Начните за минуты. Доступно на всех платформах.',
    'download.windows': 'Windows',
    'download.windows.desc': 'Windows 10/11 64-bit',
    'download.windows.btn': 'Скачать для Windows',
    'download.macos': 'macOS',
    'download.macos.desc': 'macOS 12.0 или новее',
    'download.macos.btn': 'Скачать для Mac',
    'download.linux': 'Linux',
    'download.linux.desc': 'Ubuntu, Debian, Fedora',
    'download.linux.btn': 'Скачать для Linux',
    'download.android': 'Android',
    'download.android.desc': 'Android 8.0 или новее',
    'download.android.btn': 'Скачать APK',
    'download.ios': 'iOS',
    'download.ios.desc': 'iOS 14.0 или новее',
    'download.ios.btn': 'App Store',
    'download.help': 'Нужна помощь? Смотрите',
    'download.guide': 'Руководство',
    
    // FAQ
    'faq.title': 'Часто задаваемые вопросы',
    'faq.subtitle': 'Всё что нужно знать о SecureVPN',
    'faq.q1': 'Что такое VPN и зачем он нужен?',
    'faq.a1': 'VPN шифрует ваше интернет-соединение и скрывает IP адрес. Это защищает данные от хакеров в публичных WiFi сетях и позволяет обходить гео-ограничения.',
    'faq.q2': 'Сколько устройств можно подключить?',
    'faq.a2': 'Зависит от плана. Бесплатный - 1 устройство, Стандарт - 5 устройств, Премиум - без ограничений.',
    'faq.q3': 'VPN замедлит интернет?',
    'faq.a3': 'Современные VPN используют оптимизированные протоколы. Большинство пользователей замечают менее 10% снижения скорости.',
    'faq.q4': 'Вы сохраняете логи активности?',
    'faq.a4': 'Нет. Мы работаем по принципу без логов. Мы не отслеживаем вашу активность и не делимся данными.',
    'faq.q5': 'Можно использовать для стриминга?',
    'faq.a5': 'Да! SecureVPN отлично работает для стриминга. Наши серверы оптимизированы для обхода гео-ограничений.',
    'faq.q6': 'Как установить SecureVPN?',
    'faq.a6': 'Скачайте приложение, установите и войдите в аккаунт. Приложение автоматически подключится к лучшему серверу.',
    'faq.q7': 'Какие способы оплаты?',
    'faq.a7': 'Мы принимаем карты Visa, Mastercard, PayPal и криптовалюту (Bitcoin, Ethereum).',
    'faq.q8': 'Есть гарантия возврата?',
    'faq.a8': 'Да! Все платные планы имеют 30-дневную гарантию возврата денег без вопросов.',
    
    // Contact
    'contact.title': 'Поддержка',
    'contact.subtitle': 'Наша команда поможет вам 24/7',
    'contact.getInTouch': 'Связаться',
    'contact.description': 'Есть вопросы? Наша команда поддержки всегда готова помочь.',
    'contact.email': 'Email поддержка',
    'contact.liveChat': 'Живой чат',
    'contact.liveChat.desc': 'Доступен 24/7',
    'contact.responseTime': 'Время ответа',
    'contact.responseTime.desc': 'Обычно в течение 2 часов',
    'contact.form.name': 'Имя',
    'contact.form.namePlaceholder': 'Ваше имя',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'ваш@email.com',
    'contact.form.subject': 'Тема',
    'contact.form.subjectPlaceholder': 'Чем можем помочь?',
    'contact.form.message': 'Сообщение',
    'contact.form.messagePlaceholder': 'Опишите вашу проблему...',
    'contact.form.send': 'Отправить',
    'contact.toast.title': 'Отправлено!',
    'contact.toast.desc': 'Мы ответим в течение 24 часов.',
    
    // Footer
    'footer.description': 'Ваш надёжный партнёр для безопасности онлайн.',
    'footer.product': 'Продукт',
    'footer.company': 'Компания',
    'footer.support': 'Поддержка',
    'footer.legal': 'Правовая информация',
    'footer.aboutUs': 'О нас',
    'footer.blog': 'Блог',
    'footer.careers': 'Карьера',
    'footer.press': 'Пресса',
    'footer.helpCenter': 'Центр помощи',
    'footer.contact': 'Контакты',
    'footer.status': 'Статус',
    'footer.terms': 'Условия',
    'footer.privacyPolicy': 'Конфиденциальность',
    'footer.cookiePolicy': 'Cookie',
    'footer.gdpr': 'GDPR',
    'footer.licenses': 'Лицензии',
    'footer.rights': 'Все права защищены.',
    'footer.privacy': 'Конфиденциальность',
    'footer.cookies': 'Cookies',
    
    // Dashboard
    'dashboard.home': 'Главная',
    'dashboard.connecting': 'Подключение...',
    'dashboard.connected': 'Подключено',
    'dashboard.disconnected': 'Отключено',
    'dashboard.connectSecure': 'Подключитесь для безопасности',
    'dashboard.time': 'Время',
    'dashboard.download': 'Загрузка',
    'dashboard.upload': 'Отдача',
    'dashboard.totalDownload': 'Всего загружено',
    'dashboard.totalUpload': 'Всего отдано',
    'dashboard.ping': 'Пинг',
    'dashboard.encryption': 'Шифрование',
    'dashboard.activeProtection': 'Активная защита',
    'dashboard.killSwitch': 'Kill Switch',
    'dashboard.dnsProtection': 'DNS защита',
    'dashboard.autoReconnect': 'Авто-переподключение',
    'dashboard.servers': 'Серверы',
    'dashboard.server': 'сервер',
    'dashboard.load': 'нагрузка',
    'dashboard.premium': 'Премиум',
    'dashboard.upgradePremium': 'Перейти на Премиум',
    'dashboard.upgradeDesc': 'Доступ ко всем серверам без лимитов',
    'dashboard.viewPlans': 'Смотреть планы',
  },
  uz: {
    // Navbar
    'nav.home': 'Bosh sahifa',
    'nav.features': 'Xususiyatlar',
    'nav.pricing': 'Narxlar',
    'nav.download': 'Yuklab olish',
    'nav.faq': 'FAQ',
    'nav.support': "Qo'llab-quvvatlash",
    'nav.dashboard': 'Panel',
    'nav.install': "O'rnatish",
    
    // Hero
    'hero.badge': 'Harbiy darajali shifrlash',
    'hero.title1': 'Raqamli',
    'hero.title2': "Xavfsizligingizni Ta'minlang",
    'hero.subtitle': "Tezkor VPN orqali internetda xavfsiz ishlang. Barcha qurilmalaringizda mavjud — Windows, Mac, Linux, Android va iOS.",
    'hero.cta.trial': 'Bepul boshlash',
    'hero.cta.learn': "Ko'proq bilish",
    'hero.trust.nolog': 'Log saqlanmaydi',
    'hero.trust.countries': '50+ mamlakat',
    'hero.trust.encryption': 'AES-256 Shifrlash',
    
    // Features
    'features.title': 'Nega SecureVPN?',
    'features.subtitle': "Sizni onlayn xavfsiz saqlash uchun eng yaxshi xususiyatlar",
    'features.security.title': 'Harbiy Xavfsizlik',
    'features.security.desc': "AES-256 shifrlash ma'lumotlaringizni himoya qiladi.",
    'features.speed.title': 'Tezkor Tezlik',
    'features.speed.desc': "Optimallashtirilgan serverlar tezlikni kamaytirmaydi.",
    'features.global.title': "Global Tarmoq",
    'features.global.desc': "50+ mamlakatga ulaning.",
    'features.nolog.title': 'Log Saqlanmaydi',
    'features.nolog.desc': "Biz hech qachon ma'lumotlaringizni kuzatmaymiz.",
    'features.anonymous.title': 'Anonim',
    'features.anonymous.desc': "IP manzilingizni yashiring va anonim bo'ling.",
    'features.bandwidth.title': "Cheksiz Trafik",
    'features.bandwidth.desc': "Cheklovsiz striming va yuklab olish.",
    'features.platforms': "Barcha Qurilmalarda Mavjud",
    
    // Pricing
    'pricing.title': "Oddiy va Shaffof Narxlar",
    'pricing.subtitle': "Ehtiyojingizga mos rejani tanlang. Istalgan vaqtda bekor qiling.",
    'pricing.free': 'Bepul',
    'pricing.standard': 'Standart',
    'pricing.premium': 'Premium',
    'pricing.forever': 'umrbod',
    'pricing.month': '/oy',
    'pricing.free.desc': "Oddiy foydalanuvchilar uchun asosiy himoya",
    'pricing.standard.desc': "Shaxslar uchun to'liq himoya",
    'pricing.premium.desc': "Maksimal xavfsizlik",
    'pricing.popular': 'Mashhur',
    'pricing.startFree': 'Boshlash',
    'pricing.getStarted': 'Boshlash',
    'pricing.guarantee': "30 kunlik pul qaytarish kafolati",
    'pricing.device': 'Qurilma',
    'pricing.devices': 'Qurilma',
    'pricing.unlimited': 'Cheksiz',
    'pricing.serverLocations': 'Server joylashuvi',
    'pricing.basicEncryption': 'Asosiy shifrlash',
    'pricing.limitedBandwidth': "Cheklangan (500MB/kun)",
    'pricing.unlimitedData': "Cheksiz ma'lumot",
    'pricing.prioritySupport': "Ustuvor qo'llab-quvvatlash",
    'pricing.aes256': 'AES-256 Shifrlash',
    'pricing.unlimitedBandwidth': 'Cheksiz trafik',
    'pricing.adBlocker': "Reklama bloklash",
    'pricing.emailSupport': "Email qo'llab-quvvatlash",
    'pricing.wireguard': 'AES-256 + WireGuard',
    'pricing.dedicatedIP': 'Maxsus IP',
    'pricing.247Support': "24/7 Qo'llab-quvvatlash",
    
    // Download
    'download.title': 'SecureVPN Yuklab Olish',
    'download.subtitle': "Daqiqalar ichida boshlang. Barcha platformalarda mavjud.",
    'download.windows': 'Windows',
    'download.windows.desc': 'Windows 10/11 64-bit',
    'download.windows.btn': 'Windows uchun yuklab olish',
    'download.macos': 'macOS',
    'download.macos.desc': 'macOS 12.0 yoki yangi',
    'download.macos.btn': 'Mac uchun yuklab olish',
    'download.linux': 'Linux',
    'download.linux.desc': 'Ubuntu, Debian, Fedora',
    'download.linux.btn': 'Linux uchun yuklab olish',
    'download.android': 'Android',
    'download.android.desc': 'Android 8.0 yoki yangi',
    'download.android.btn': 'APK yuklab olish',
    'download.ios': 'iOS',
    'download.ios.desc': 'iOS 14.0 yoki yangi',
    'download.ios.btn': 'App Store',
    'download.help': "Yordam kerakmi? Ko'ring",
    'download.guide': "O'rnatish qo'llanmasi",
    
    // FAQ
    'faq.title': "Ko'p so'raladigan savollar",
    'faq.subtitle': "SecureVPN haqida bilishingiz kerak bo'lgan hamma narsa",
    'faq.q1': "VPN nima va menga nega kerak?",
    'faq.a1': "VPN internet ulanishingizni shifrlaydi va IP manzilingizni yashiradi. Bu ma'lumotlaringizni himoya qiladi va geo-cheklovlarni chetlab o'tishga yordam beradi.",
    'faq.q2': "Nechta qurilmani ulash mumkin?",
    'faq.a2': "Rejaga bog'liq. Bepul - 1 qurilma, Standart - 5 qurilma, Premium - cheksiz.",
    'faq.q3': 'VPN internetni sekinlashtiradimi?',
    'faq.a3': "Zamonaviy VPNlar optimallashtirilgan protokollardan foydalanadi. Ko'pchilik foydalanuvchilar 10% dan kam sekinlashuvni sezadi.",
    'faq.q4': 'Siz faoliyat loglarini saqlaysizmi?',
    'faq.a4': "Yo'q. Biz log saqlamaymiz. Faoliyatingizni kuzatmaymiz va ma'lumotlarni ulashmaymiz.",
    'faq.q5': 'Striming uchun ishlatsa bo\'ladimi?',
    'faq.a5': "Ha! SecureVPN striming uchun ajoyib ishlaydi. Serverlarimiz geo-cheklovlarni chetlab o'tish uchun optimallashtirilgan.",
    'faq.q6': "SecureVPN-ni qanday o'rnatish mumkin?",
    'faq.a6': "Ilovani yuklab oling, o'rnating va hisobingizga kiring. Ilova avtomatik ravishda eng yaxshi serverga ulanadi.",
    'faq.q7': "Qanday to'lov usullari qabul qilinadi?",
    'faq.a7': "Biz Visa, Mastercard, PayPal va kriptovalyutani (Bitcoin, Ethereum) qabul qilamiz.",
    'faq.q8': "Pul qaytarish kafolati bormi?",
    'faq.a8': "Ha! Barcha pullik rejalarda 30 kunlik pul qaytarish kafolati mavjud.",
    
    // Contact
    'contact.title': "Qo'llab-quvvatlash",
    'contact.subtitle': 'Jamoamiz sizga 24/7 yordam beradi',
    'contact.getInTouch': "Bog'lanish",
    'contact.description': "Savollaringiz bormi? Qo'llab-quvvatlash jamoamiz doimo yordam berishga tayyor.",
    'contact.email': "Email qo'llab-quvvatlash",
    'contact.liveChat': 'Jonli chat',
    'contact.liveChat.desc': '24/7 mavjud',
    'contact.responseTime': 'Javob vaqti',
    'contact.responseTime.desc': "Odatda 2 soat ichida",
    'contact.form.name': 'Ism',
    'contact.form.namePlaceholder': 'Ismingiz',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'sizning@email.com',
    'contact.form.subject': 'Mavzu',
    'contact.form.subjectPlaceholder': 'Qanday yordam bera olamiz?',
    'contact.form.message': 'Xabar',
    'contact.form.messagePlaceholder': "Muammoingizni tasvirlang...",
    'contact.form.send': "Xabar jo'natish",
    'contact.toast.title': "Jo'natildi!",
    'contact.toast.desc': '24 soat ichida javob beramiz.',
    
    // Footer
    'footer.description': "Onlayn xavfsizlik uchun ishonchli hamkoringiz.",
    'footer.product': 'Mahsulot',
    'footer.company': 'Kompaniya',
    'footer.support': "Qo'llab-quvvatlash",
    'footer.legal': 'Huquqiy',
    'footer.aboutUs': 'Biz haqimizda',
    'footer.blog': 'Blog',
    'footer.careers': 'Karyera',
    'footer.press': 'Matbuot',
    'footer.helpCenter': 'Yordam markazi',
    'footer.contact': "Bog'lanish",
    'footer.status': 'Holat',
    'footer.terms': 'Shartlar',
    'footer.privacyPolicy': 'Maxfiylik',
    'footer.cookiePolicy': 'Cookie',
    'footer.gdpr': 'GDPR',
    'footer.licenses': 'Litsenziyalar',
    'footer.rights': 'Barcha huquqlar himoyalangan.',
    'footer.privacy': 'Maxfiylik',
    'footer.cookies': 'Cookies',
    
    // Dashboard
    'dashboard.home': 'Bosh sahifa',
    'dashboard.connecting': 'Ulanmoqda...',
    'dashboard.connected': 'Ulangan',
    'dashboard.disconnected': 'Uzilgan',
    'dashboard.connectSecure': 'Xavfsiz ulanish uchun ulaning',
    'dashboard.time': 'Vaqt',
    'dashboard.download': 'Yuklab olish',
    'dashboard.upload': 'Yuklash',
    'dashboard.totalDownload': 'Jami yuklab olish',
    'dashboard.totalUpload': 'Jami yuklash',
    'dashboard.ping': 'Ping',
    'dashboard.encryption': 'Shifrlash',
    'dashboard.activeProtection': 'Faol Himoya',
    'dashboard.killSwitch': 'Kill Switch',
    'dashboard.dnsProtection': 'DNS Himoya',
    'dashboard.autoReconnect': 'Avtomatik qayta ulanish',
    'dashboard.servers': 'Serverlar',
    'dashboard.server': 'server',
    'dashboard.load': 'yuklanish',
    'dashboard.premium': 'Premium',
    'dashboard.upgradePremium': "Premium-ga o'tish",
    'dashboard.upgradeDesc': "Barcha serverlarga cheksiz tezlik bilan kirish",
    'dashboard.viewPlans': "Rejalarni ko'rish",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
